library (shiny)
library (shinydashboard)
library (DT)
library (plyr)
library (dplyr)
library (ggplot2)
library (gridExtra)
library (gtable)
library (scales)
library (dataRetrieval)
library (zoo)
library (lubridate)
library (smwrStats)
library (mgcv)

options(DT.options = list(pageLength = 7, language = list(search = 'Filter:')))
